# theme: jekyll-theme-minimal
# title: Hi, I'm Alex!
# description: Hi! I’m currently a senior software engineer in the Bay Area. I graduated from Duke University with a double concentration in Computer Science and Economics.
